### ISSUE TITLE
Updating the Xtext Community Website

### ISSUE THREAD

**Issue by miklossy** [balzac-lang/balzac#71]
Hello Balzac team,

The Xtext team would like to update the [Xtext community website](https://www.eclipse.org/Xtext/community.html) listing all the cool projects people are building around Xtext/Xtend.

See also the corresponding [GitHub issue](https://github.com/eclipse/xtext/issues/1541) and [Bugzilla ticket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=328477).

If you are interested that the Balzac project is listed there, please provide the following information as a comment to this issue:

```
<tr>
	<td><a href="project_link">project_name</a></td>
	<td>project_description_max_2_sentences</td>
	<td>license</td>
	<td>category</td>
	<td>author(s)</td>
</tr>

```
We will then update the Xtext community website and get it online as soon as possible.

Thanks!
Tamás

**Comment by natzei** [comment]
Hello Tamas,
I'd be honoured to see my project in the Xtext community website:
```
<tr>
	<td><a href="https://github.com/balzac-lang/balzac">Balzac Language</a></td>
	<td>Balzac is a domain-specific language to write Bitcoin transactions. <a href="https://balzac-lang.xyz">Online editor</a> and <a href="https://docs.balzac-lang.xyz/">documentation</a>.</td>
	<td>Apache License 2.0</td>
	<td>Language</td>
	<td>Nicola Atzei</td>
</tr>
```

**Comment by miklossy** [comment]
Thank you @natzei !

**Comment by miklossy** [comment]
The `Balzac Language` project has been added to the [Xtext community website](https://www.eclipse.org/Xtext/community.html).
